version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 9900 --reload
    volumes:
      - .:/code
    ports:
      - "9900:9900"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:ASdfrewq6677!!@db/postgres
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ASdfrewq6677!!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  default:
